WWE-772 [Agent Api Simulator] Issues with multi-tabs
GenesysPureEngage/agent-api-simulator pull request #116
Opened 2022-07-12 13:31 UTC by VadymKondra

Reason:
The issue was caused because of the algorithm which works when the user creates new tab. When user run new tab, the program creates new session and switch it with the cometd session already existed and the server-side events were published to the last opened tab.
Solution:
Instead of single session for last opened tab API simulator will use an array with the all opened tabs sessions. When the user creates new tab, sessions of the old tabs will be saved and will continue to recieve published events.

2022-07-13 17:58 UTC, sblecon commented on src/service/controllers/messaging.js
> +		var session = sessions[userName] && sessions[userName].length && sessions[userName][0];
Is there a risk to return always the first session associated to the use in front?

2022-07-15 16:03 UTC, sblecon submitted a review, later dismissed

2022-07-19 08:30 UTC, Karkhutvy requested changes

2022-07-19 08:30 UTC, Karkhutvy commented on src/service/controllers/messaging.js
> +
Please, remove empty rows added

2022-07-19 08:30 UTC, Karkhutvy commented on src/service/controllers/messaging.js
> +
Please, remove empty rows added

2022-07-19 08:30 UTC, Karkhutvy commented on src/service/controllers/messaging.js
> +
Please, remove empty rows added

2022-07-19 08:43 UTC, VadymKondra commented on src/service/controllers/messaging.js
> +
Done

2022-07-19 08:43 UTC, VadymKondra commented on src/service/controllers/messaging.js
> +
Done

2022-07-19 08:45 UTC, sblecon approved these changes

2022-07-19 09:01 UTC, Karkhutvy approved these changes

2022-07-19 09:06 UTC, merged